### ISSUE TITLE
Add T121 WITH (excluding RECURSIVE) in query expression support

### ISSUE THREAD

**Issue by TedCraft** [red-soft-ru/shardingsphere#40]
--------------------------------------------------------------------------------------------------------------------------
You have an error in your SQL syntax: WITH T121 AS (SELECT AGENT_CODE AGENT_NAME COMMISSION FROM AGENTS) SELECT C.CUST_NAME C.CUST_CITYT.COMMISSION FROM CUSTOMER c LEFT JOIN T121 T ON T.AGENT_CODE = C.AGENT_CODE no viable alternative at input 'WITH' at line 1 position 1 near @01:4='WITH'<71>1:1
--------------------------------------------------------------------------------------------------------------------------

**Comment by makssent** [comment]
"Table or view `T121` does not exist."
